### ISSUE TITLE
Stop service when app killed

### ISSUE THREAD

**Issue by Farrukh1198** [easazade/android-long-task#8]
How to stop the service when app is killed or exited? I successfully initialized the service, it's working fine when I minimize app. But it still working when I exit app and I want to stop it when I exit the app. Please help me.

**Comment by easazade** [comment]
you can watch for flutter app lifecycle state called `AppLifecycleState.detached`.
checkout this [stackoverflow](https://stackoverflow.com/questions/52074265/flutter-detect-killing-off-the-app) answer
may I ask what is the point of using service when you want to kill it when the app is killed?

**Comment by Farrukh1198** [comment]
Thank you for your reply. I'm making taxi driver app and they can't get
orders when they minimizes the app. And now they're getting orders even if
they are not working at the moment.
Or can I show stop button on  service notification?

чт, 27 янв. 2022 г., 8:27 AM alireza easazade ***@***.***>:

**Comment by easazade** [comment]
there is no stop or cancel button on notification feature in this plugin. PRs are accepted though :))

**Comment by Farrukh1198** [comment]
Ok, thanks.

чт, 27 янв. 2022 г., 2:54 PM alireza easazade ***@***.***>:

**Comment by Farrukh1198** [comment]
Another question. I tried to build release app. But it's not working
properly

чт, 27 янв. 2022 г., 2:56 PM Фаррух Ахунов ***@***.***>:

**Comment by easazade** [comment]
have you annotated the `serviceMain` function with

```dart
@pragma('vm:entry-point')
serviceMain() async {
```

also take look at this [issue](https://github.com/easazade/android-long-task/issues/7)

**Comment by Farrukh1198** [comment]
Yes, I did. I'm rebuilt app and now it's work fine 👌👍👍 thank you so much
for your reply and your plugin it's the best plugin for foreground service
👍. And another question can I work with multiple services using this
plugin?

чт, 27 янв. 2022 г., 8:45 PM alireza easazade ***@***.***>:

**Comment by easazade** [comment]
No. you can only run one Foreground Service using this plugin. I also never seen an android app run 2 foreground services at the same time. even if it is possible, if you want to handle multiple tasks in services, it's best to use one service for all of them since in newer android versions there is always a possibility that OS might kill the foreground service. (it's a low possibility). if you run multiple services. you increase this possibility. that being said you may need to show multiple notifications since you are running different tasks and you might want to show user the progress for each task. I think this can be achieved using [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) plugin to show different notifications for each task you are running in you're foreground service

**Comment by Farrukh1198** [comment]
Ok, got it. Last question, sorry for being annoying, when I minimize the
app service starts when I return to the app service stops but I get this
message
"Tried to send a platform message to Flutter, but FlutterJNI was detached
from native C++."  Is it related to long task plugin? After that my service
doesn't work properly. Like I said I use service to get data from service
via SSE(Server Sents Events) but after about 30 mins  I'm not getting any
messages.

чт, 27 янв. 2022 г., 11:25 PM alireza easazade ***@***.***>:

**Comment by easazade** [comment]
not sure what you're doing
